services:
  postgres:
    image: postgres:16
    container_name: central-associacao-db
    restart: unless-stopped

    env_file:
      - path: .env
        required: false
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-central_associacao}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

    ports:
      - "2345:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 3s
      timeout: 3s
      retries: 10

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: central-associacao-api
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    env_file:
      - path: .env
        required: false
      - path: backend/.env
        required: false
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-central_associacao}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LDAP_API_URL: ${LDAP_API_URL:-https://hub.hsjeronimo.com.br/api/v1/ldap/usuarios}
      LDAP_API_TOKEN: ${LDAP_API_TOKEN:-${APP_KEY_PROD}}
      APP_KEY_PROD: ${APP_KEY_PROD}
      APP_KEY_TEST: ${APP_KEY_TEST}

  frontend:
    build:
      context: ./frontend

    container_name: central-associacao-web
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src

    depends_on:
      - backend

    ports:
      - "5173:5173"

    env_file:
      - path: .env
        required: false
    environment:
      VITE_API_URL: ${VITE_API_URL:-/central-associacao-api}

volumes:
  postgres_data:
